#!/usr/bin/env node

//requirements 
var Twit = require('twit')
var express=require('express');
var request = require('request');
var router = express.Router();
var cors = require('cors'); 

var T = new Twit({
  consumer_key:         'zkajjNReeAMWwVgp1FSHAT2cK',
  consumer_secret:      'Djv3mm2JSEL9Omc3hq78zk8YSGr8cglGAl9UIX58vu0CYosAaF',
  access_token:         'YOUR ACCESS TOKEN HERE',
  access_token_secret:  'YOUR ACCESS TOKEN SECRET HERE',
  timeout_ms:           60*1000,  // optional HTTP request timeout to apply to all requests. 
})

var app = express();
app.use(cors());  
//Setup rotuing for app
app.use(express.static(__dirname + '/public'));

var jsonData=[];

app.get('/tweetsGet',function(req,res){

	var resData=jsonData;
	jsonData=[];
//returning json data of the streamed tweets
	return res.json(resData);

});

console.log("Streaming Live Twitter Feeds...");
//streaming tweets from the whole world,with english language
var stream = T.stream('statuses/filter',{ locations : [-180,-90,180,90] , language: 'en' } )
stream.on('tweet', function (tweet) {

//error handling conitions
	if( tweet.place != null )
	  	if( tweet.place.hasOwnProperty('bounding_box') )
	  		if( tweet.place.bounding_box.coordinates !== null )
	  			if(  tweet.place.hasOwnProperty('full_name') )
	  				if( tweet.hasOwnProperty('user') )
	  					if( tweet.user.hasOwnProperty('profile_image_url') )  						
	  						if( tweet.hasOwnProperty('text') )
	  							if( tweet.hasOwnProperty('source') ){
									  jsonData.push(
									  {
									  	"coordinates" : tweet.place.bounding_box.coordinates ,
									  	"place_name" : tweet.place.full_name ,
									  	"profile_image_url" : tweet.user.profile_image_url,
									  	"text" : tweet.text,
									  	"source" : tweet.source 
									  }
									  	);
					  					  console.log(tweet);

	  							}

});

//listen on port 5000
app.listen(process.env.PORT || 5000  , function () {
	console.log('example app listening on port 5000!');
});
